version: '3'

services:
    server:
        container_name: djproject
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./Dockerfile
        entrypoint: /code/entrypoint.sh
        expose:
            - 8000     
        environment:
            ALLOWED_HOSTS: ${ALLOWED_HOSTS}
            CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
   
volumes:
    static_volume: {}