services:
  - type: web
    plan: free
    name: floorhosting
    runtime: python
    buildCommand: "./build.sh"
    startCommand: cd backend && python -m gunicorn floorhosting.asgi:application -k uvicorn.workers.UvicornWorker
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_DEBUG
        value: true