# Generated by Django 5.1.7 on 2025-04-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameservers', '0002_service_servicefeature_delete_gameserver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Base monthly price', max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='discount_12_month',
            field=models.IntegerField(default=10, help_text='Discount percentage for 12-month subscription'),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_24_month',
            field=models.IntegerField(default=20, help_text='Discount percentage for 24-month subscription'),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_48_month',
            field=models.IntegerField(default=30, help_text='Discount percentage for 48-month subscription'),
        ),
    ]
